### ISSUE TITLE
Don't mark up extension titles as anchor tags

### ISSUE THREAD

**Issue by universalhandle** [twomice/org.civicrm.extensionsui#13]
Okay, getting into bikeshedding territory here, so disregard this if you like.

I noticed links to the extension detail screen are marked up as anchor tags with the ng-click directive. I noticed this because when I hovered my mouse over the links, the browser displayed "http://example.org/civicrm/a" in the status bar. It's not a big deal, but it's a little confusing.

The Ng-click directive can be applied to any HTML element, so you could do something like this:

```html
<span
  ng-click="showOverlay(value.key, value.crmExt_parentname)"
  class="crm-ext-detail-link">Extension name here
</span>

<style>
.crm-ext-detail-link {
  color: #2786c2;
  cursor: pointer;
}
</style>
```

**Comment by twomice** [comment]
Thanks @GinkgoFJG !

**Comment by universalhandle** [comment]
The bike shed should be red, damn you!
