### ISSUE TITLE
Colour for each line if enabled/disabled

### ISSUE THREAD

**Issue by mattwire** [twomice/org.civicrm.extensionsui#16]
One of the nice things about the old extensions manager is the colour for enabled/disabled.  Makes it really easy to see at a glance whether an extension is enabled - can we do the same for the new UI?

**Comment by twomice** [comment]
HI @mattwire I think this is taken care of in #14. If you check out the master repo after ef50330, you should see colors. I'll close this as a duplicate for now, but please re-open if there's more to do. Thanks!

**Comment by mattwire** [comment]
It is! Thankyou
