### ISSUE TITLE
Improve navigation/discoverability of new UI

### ISSUE THREAD

**Issue by universalhandle** [twomice/org.civicrm.extensionsui#2]
If we change nothing else, instructions for how to get to the extension UI (currently under "Usage" in README.md) should go into the extension description so users don't have to go find the readme.

Since this extension is supposed to replace the core UI, I would recommend updating the item in the menu to use our URL instead. Since the extension is still somewhat experimental, I would include a link on the new UI back to "Legacy screen" or whatever we want to call it.

**Comment by twomice** [comment]
See comments in commit ed45a9b.
