### ISSUE TITLE
Missing extensions are not handled gracefully

### ISSUE THREAD

**Issue by universalhandle** [twomice/org.civicrm.extensionsui#6]
If you delete an installed extension from the filesystem without first uninstalling it, the system should report it as "missing." If you already have the extensions UI pulled up when you do this, and then click the refresh button, the UI does this in more or less the same way as the core UI. I think there is room for improvement here:

- Missing extensions should be styled so as to be more obvious. (The core UI does a decent job of this.)
- If we are trying to make this UI more user-friendly than core's perhaps we should explain how this might have happened or some possible next steps.
- Unlike the core UI, this one doesn't offer a mechanism by which to disable/uninstall missing extensions.

If you have an extension in a missing state and you don't already have the UI pulled up, you can't do it. Instead you get:

> Error
> Error messageCRM_Extension_Exception_MissingException: Unknown extension: nz.co.fuzion.relatedpermissions in CRM_Extension_Container_Collection->getContainer() (line 150 of /usr/local/lib/civicrm-buildkit/build/d47/sites/all/modules/civicrm/CRM/Extension/Container/Collection.php).
> The website encountered an unexpected error. Please try again later.

**Comment by twomice** [comment]
Agreed, this is a significant issue. Need to work on a solution. Thanks, Frank.

**Comment by twomice** [comment]
Surprisingly, the fatal error you mention isn't caused by this extension. It happens on every angular-based page when any extension is missing, whether this extension is installed or not. See here: https://issues.civicrm.org/jira/browse/CRM-20240 @GinkgoFJG That ticket makes me feel a little crazy; can you try to reproduce it yourself and tell me if you see the same thing?

**Comment by twomice** [comment]
These two commits provide relevant improvements:

1. Allow disabling of missing extensions
1. Highlight missing extensions more visibly in list
1. Provide more help for missing extensions in detailed overlay.

Screenshot: A missing extension as shown in the list:
![missing-row](https://cloud.githubusercontent.com/assets/759449/23819735/ec888786-05cf-11e7-8cce-0024056dcee6.png)

Screenshot: A missing extension as shown in the detailed overlay:
![missing-overlay](https://cloud.githubusercontent.com/assets/759449/23819736/f133b616-05cf-11e7-9acc-63291ec65ee5.png)

**Comment by twomice** [comment]
The remaining item in this ticket relates to CRM-20240 ("Fatal error on all Angular pages if an extension is missing"). I'd like to let that issue be handled separately. 

I'm inclined to close this. @GinkgoFJG do you concur?

**Comment by universalhandle** [comment]
I commented on CRM-20240, which I think is a bit of a red herring.

However, I think there are still some issues to deal with here:

- See screenshot below. The error message says the extension cannot be loaded from the following path but does not actually give the path.
- When I tried it, clicking "Disable" on my missing extension did not refresh the UI. After clicking "Refresh" the status is updated to "Disabled (Missing)," which is correct, but I think the user shouldn't need to manually request a refresh.

![screenshot from 2017-03-20 11-48-52](https://cloud.githubusercontent.com/assets/871819/24108372/c642cb90-0d63-11e7-9ddc-107a63f9c768.png)

**Comment by twomice** [comment]
Regarding _When I tried it, clicking "Disable" on my missing extension did not refresh the UI. After clicking "Refresh" the status is updated to "Disabled (Missing)," which is correct, but I think the user shouldn't need to manually request a refresh._:
I tried this now on master and cannot reproduce. Perhaps it was fixed in an earlier commit. Probably best to open a separate ticket if it still comes up.

PR #20 addresses _The error message says the extension cannot be loaded from the following path but does not actually give the path._

**Comment by universalhandle** [comment]
@twomice, I opened up a PR to address one last issue that crept in with the fix for #15. If you approve the PR, I think we can close this issue.

**Comment by twomice** [comment]
@GinkgoFJG If you mean PR #22 , that's merged. Can you confirm that, and close?

**Comment by twomice** [comment]
BTW, I tested now on master and observe proper behavior for an installed-but-missing extension, including proper behavior when clicking "Disable" and then "Uninstall", like so:

* **installed-but-missing**: Status reads "Enabled (Missing)", and pop-up shows full and correct message, e.g., "The extension file cannot be loaded from its path. Please restore the file or disable the extension. /var/www/d7civi47latest/sites/default/files/civicrm/ext/biz.jmaconsulting.simpleunsub"
* **click "Disable":** Status changes to "Disabled (Missing)". 
* **click "Uninstall":** Extension is removed from list.

**Comment by universalhandle** [comment]
Confirming that PR #22 is the one that I meant, and closing!
