### ISSUE TITLE
Replace existing extensions manager menu item

### ISSUE THREAD

**Issue by twomice** [twomice/org.civicrm.extensionsui#8]
At the moment, the only way to access this UI is by manually entering a URL. I'd like to add a menu override so that requests to /civicrm/admin/extensions?reset=1 are redirected to /civicrm/a/#/extensions, in order to have this UI replace the core/legacy UI.

**Comment by universalhandle** [comment]
See also: #2.

**Comment by twomice** [comment]
Closing as duplicate of #2.
